In [1]:
# Author: Jayme Anchante
# Date:
Sys.Date()

[1] "2018-05-06"

# 1. Functions and arguments
In R, functions are defined as:

`function(arg1, arg2, ...)`

For example `runif()` returns random numbers from an uniform distribution:

`runif(n, min=0, max=1)`

In [2]:
runif(n=10, min=1, max=10)

[1] 1.902306 8.890492 1.433604 4.760032 4.808930 8.630758 5.235705 8.037342
 [9] 3.749381 7.657758

Arguments with default values could be omitted:

In [3]:
runif(10)

[1] 0.8622453 0.8727190 0.9093544 0.5315791 0.2953695 0.1271526 0.1075497
 [8] 0.9313032 0.6559948 0.5618833

If arguments are named, the order is unimportant:

In [4]:
runif(min=1, max=100, n=10)

[1] 89.548237 98.785675 28.034969 77.062036 38.452432  6.741032 64.085197
 [8] 82.774540 87.784203 99.795579

Named and unnamed arguments can be used, since unnamed ones are in the correct position:

In [5]:
runif(10, max=100, min=1)

[1] 76.99833 58.58678 28.02773 60.42673 74.67406 93.41541 44.72833 78.55861
 [9] 97.76670 28.76365

## 1.1. Other types of arguments

For example: `sample()`function:

```sample(x, size, replace=FALSE, prob=NULL)```

> `x` and `size` must be specified

> `replace` is logical: `TRUE` (`T`) or `FALSE` (`F`)

> `prob` is oprtional

For example: `plot()` function:

```plot(x, y, ...)```

> "`...`" allow specify arguments from other functions

To see all arguments from a function, use `args()`:

In [6]:
args(sample)

function (x, size, replace = FALSE, prob = NULL) 
NULL

# 2. Help

In [7]:
?runif

In [8]:
help(runif)

In [9]:
# searching for function names which contain some word:
apropos('mod')

[1] "!.hexmode"                  "!.octmode"                 
 [3] "[.hexmode"                  "[.octmode"                 
 [5] "&.hexmode"                  "&.octmode"                 
 [7] "|.hexmode"                  "|.octmode"                 
 [9] "as.character.hexmode"       "as.character.octmode"      
[11] "as.data.frame.model.matrix" "as.hexmode"                
[13] "as.octmode"                 "expand.model.frame"        
[15] "file.mode"                  "format.hexmode"            
[17] "format.octmode"             "is.empty.model"            
[19] "Mod"                        "mode"                      
[21] "mode<-"                     "model.extract"             
[23] "model.frame"                "model.frame.default"       
[25] "model.matrix"               "model.matrix.default"      
[27] "model.matrix.lm"            "model.offset"              
[29] "model.response"             "model.tables"              
[31] "model.weights"              "modifyList"                
[33] "print.hexmode"              "print.octmode"             
[35] "storage.mode"               "storage.mode<-"            
[37] "Sys.chmod"                  "xor.hexmode"               
[39] "xor.octmode"

In [10]:
apropos('model')

[1] "as.data.frame.model.matrix" "expand.model.frame"        
 [3] "is.empty.model"             "model.extract"             
 [5] "model.frame"                "model.frame.default"       
 [7] "model.matrix"               "model.matrix.default"      
 [9] "model.matrix.lm"            "model.offset"              
[11] "model.response"             "model.tables"              
[13] "model.weights"

In [11]:
# search for functions that contain a word in any part of its documentation

help.search('palavra')

No vignettes or demos or help files found with alias or concept or
title matching ‘palavra’ using fuzzy matching.

In [12]:
# In-browser help

help.start()

starting httpd help server ... done


If the browser launched by '/usr/bin/xdg-open' is already running, it
    is *not* restarted, and you must switch to its window.
Otherwise, be patient ...


The R-core contains some basic packages (not all are loaded in the default R initialization). To list all loaded packages:

In [13]:
search()

[1] ".GlobalEnv"        "jupyter:irkernel"  "package:stats"    
 [4] "package:graphics"  "package:grDevices" "package:utils"    
 [7] "package:datasets"  "package:methods"   "Autoloads"        
[10] "package:base"

To load a package:

In [14]:
library(lattice)

In [15]:
require(MASS)

Loading required package: MASS


In [16]:
search()

[1] ".GlobalEnv"        "package:MASS"      "package:lattice"  
 [4] "jupyter:irkernel"  "package:stats"     "package:graphics" 
 [7] "package:grDevices" "package:utils"     "package:datasets" 
[10] "package:methods"   "Autoloads"         "package:base"

Loading a package makes all its functions available to use. To install a package:

In [17]:
install.packages('devtools')

Installing package into ‘/home/jayme/.R/library’
(as ‘lib’ is unspecified)


To verify available libraries and if packages can be updated:

In [18]:
packageStatus()

Number of installed packages:
                        
                         ok upgrade unavailable
  /home/jayme/.R/library 82       1           1
  /usr/lib/R/library     23       6           0

Number of available packages (each package counted only once):
                                                 
                                                  installed not installed
  http://cran.revolutionanalytics.com/src/contrib        98         12400

To update all packages:

In [19]:
# update.packages()

# 3. Creating functions

In [20]:
hello.world <- function() {
    # writting a simple 'Hello world!' function
    writeLines('Hello world!')
}

In [21]:
hello.world()

Hello world!


In [22]:
hello.world <- function(text) {
    # 'Hello world!' function with an argument
    writeLines(text)
}

In [23]:
hello.world('Function are cool!')

Function are cool!


## 3.1. Exercise 1

In [24]:
runif(n=30, min=0, max=1)

[1] 0.872982278 0.695564139 0.501311656 0.627183807 0.395181500 0.913016979
 [7] 0.648826470 0.734667994 0.234525848 0.220143706 0.509767893 0.037239135
[13] 0.174052828 0.930530837 0.140446229 0.687360080 0.763664719 0.246094502
[19] 0.885115505 0.888883556 0.483687222 0.414011896 0.863456741 0.981744172
[25] 0.334438428 0.000597930 0.604175670 0.036397291 0.857140331 0.008650454

In [25]:
runif(n=30, min=-5, max=5)

[1] -1.57355897  0.84090750  2.71393059  0.03069033  3.52572277 -3.83266531
 [7] -2.25460164  0.68211991 -3.83087686  1.13898173 -0.84961620 -2.74863191
[13]  1.25686958  0.68510744  0.82423743 -0.02359114 -0.66609533 -1.04920012
[19]  3.14938871 -2.81708397 -3.10669175  0.40039991 -0.83356519 -0.16436602
[25]  0.94276862  1.74947217 -4.07857177 -4.72582790  0.47066342  4.88147900

In [26]:
runif(n=30, min=10, max=500)

[1]  94.62415 476.41147  12.13118 465.28191 199.29837  42.57480 457.95634
 [8] 356.23431  24.88770  12.49133 214.95695 144.95590  92.90688 452.46607
[15] 336.62751 484.06963 118.12162 357.09814 281.08283 193.51086 431.49261
[22]  84.54326 492.77570 375.81257 142.79876  37.83994 418.82014 417.22226
[29] 469.15245  43.35355

In [27]:
?"+"

In [28]:
sum_function <- function(x, y) {
    # sum two numbers, x and y
    sum(x, y)
}

In [29]:
sum_function(4, 8)

[1] 12

In [30]:
dice <- function(n) {
     # simulate the throws of a dice
     sample(x=1:6, size=n, replace=TRUE)
}

In [31]:
dice(5)

[1] 6 6 6 5 1

In [32]:
dices <- function(n) {
    # simulate the throws of a dice
    first_dice <- sample(x=1:6, size=n, replace=TRUE)
    second_dice <- sample(x=1:6, size=n, replace=TRUE)
    print(paste(first_dice, ', ', second_dice, sep=''))
}

In [33]:
dices(5)

[1] "6, 3" "5, 5" "5, 3" "1, 6" "5, 3"


# 4. Objects
*Object* is a symbol or a variable capable of storing values or data structures

*Class* if the definition of an object, it describes it and how it is going to be manipulated by different functions

*Method* are generic functions that execute tasks according to each class

In [34]:
methods(plot)

 [1] plot.acf*            plot.correspondence* plot.data.frame*    
 [4] plot.decomposed.ts*  plot.default         plot.dendrogram*    
 [7] plot.density*        plot.ecdf            plot.factor*        
[10] plot.formula*        plot.function        plot.hclust*        
[13] plot.histogram*      plot.HoltWinters*    plot.isoreg*        
[16] plot.lda*            plot.lm*             plot.mca*           
[19] plot.medpolish*      plot.mlm*            plot.ppr*           
[22] plot.prcomp*         plot.princomp*       plot.profile*       
[25] plot.profile.nls*    plot.raster*         plot.ridgelm*       
[28] plot.shingle*        plot.spec*           plot.stepfun        
[31] plot.stl*            plot.table*          plot.trellis*       
[34] plot.ts              plot.tskernel*       plot.TukeyHSD*      
see '?methods' for accessing help and source code

In [35]:
# x recieves 2, becoming an object
# <- is the attribution operator

x <- 2

In [36]:
# to see x contents, simply:

x

[1] 2

In [37]:
x <- 2
y <- 4

# the same as:
x <- 2; y <- 4

In [38]:
# arithmetic operation

x + y

[1] 6

In [39]:
# objects can store different data structure
# y prior value is supercripted

y <- runif(10)

In [40]:
y

[1] 0.7984738 0.5409387 0.2925125 0.9172707 0.4312471 0.7160001 0.7925142
 [8] 0.9642217 0.7970833 0.8892721

## 4.1. Object names

* Can be letters, numbers, "_" and "."

* Can't begin with a number and/or dot

* Can't have spaces

* Avoid accents

* Avoid already declared function names

* Object names are case sensitive

# 4.2. Managing the desktop

In [41]:
# list objects created

ls()

[1] "dice"         "dices"        "hello.world"  "sum_function" "x"           
[6] "y"

In [42]:
# removes an object

rm(x)

In [43]:
rm(x, y)

Warning message in rm(x, y):
“object 'x' not found”

In [44]:
# removes all objects:

rm(list = ls())

## 4.2. Exercise 2

In [45]:
# 1.

x <- 32 + 16 ** 2 - 25 ** 3

In [46]:
# 2.

y <- x / 345

In [47]:
# 3.

random_values <- runif(n=30, min=10, max=50)

In [48]:
# 4.

rm(y)

In [49]:
# 5.

rm(list = ls())

In [50]:
# 6.

apropos('pois')
help(rpois)
rpois(n=100, lambda=5)

[1] "dpois"        "poisson"      "poisson.test" "ppois"        "qpois"       
[6] "quasipoisson" "rpois"

[1]  8  4  7  4  4  7  7  4  8  5  6  7  5  6  2  2  5  7  2  5  3  4  9  5  7
 [26]  7  5  3  3  1 10  3  4  5  8  1  3  2  4  5  6  4  4  3  7  6  6  4  3  4
 [51]  3  2  5  5  7  6  3  7  1  4 12  6  4  5  7  2  5  4  4  3  4  4  6  3  4
 [76]  5  6  4  4  6  4  6  1  8  5  3  6  1  7  5  8  7  6  3  6  2  7  6  4  6

# 5. Types and object classes

R has two basic types of vectors:

* Atomic vectors: can only contain one type of element

> double

> integer

> character

> logical

> complex

> raw

* Lists aka recursive vectors because they can contain other lists, can contain mixed types of elements

A vector is an unidimensional structure, but we can work with structures of more than one dimension, created from unidimensional structures. An object with several dimensions has a class. The `typeof()` function determines the object type, whereas the `class()` determines the object class:

In [51]:
x <- c(2, 4, 6)
typeof(x)

[1] "double"

In [52]:
class(x)

[1] "numeric"

In [53]:
x <- c(2L, 4L, 6L)
typeof(x)

[1] "integer"

In [54]:
class(x)

[1] "integer"

In [55]:
x <- c('a', 'b', 'c')
typeof(x)

[1] "character"

In [56]:
class(x)

[1] "character"

In [57]:
x <- c(TRUE, FALSE, TRUE)
typeof(x)

[1] "logical"

In [58]:
class(x)

[1] "logical"

In [59]:
x <- c(2 + 1i, 4 + 1i, 6 + 1i)
typeof(x)

[1] "complex"

In [60]:
class(x)

[1] "complex"

In [61]:
x <- raw(3)
typeof(x)

[1] "raw"

In [62]:
class(x)

[1] "raw"

## 5.1. Numeric vectors

Ordered collection of numbers, unidimenional structure

Using the `c()`function to create vectors:

In [63]:
num <- c(10, 5, 2, 4, 8, 9)
num

[1] 10  5  2  4  8  9

In [64]:
typeof(num)

[1] "double"

In [65]:
class(num)

[1] "numeric"

To force a number into integer we need the *L* suffix

In [66]:
x <- c(10L, 5L, 2L, 4L, 8L, 9L)
x

[1] 10  5  2  4  8  9

In [67]:
typeof(x)

[1] "integer"

In [68]:
class(x)

[1] "integer"

One of the differences between *numeric* and *integer* is that integer uses less storage space

In [69]:
object.size(num)

88 bytes

In [70]:
object.size(x)

72 bytes

### 5.1.1. Numeric representation

The numbers displayed are a simplified representation of the numbers stored in memory

In [71]:
x <- runif(10)
x

[1] 0.52906946 0.72586459 0.92717495 0.29825008 0.87389428 0.37516016
 [7] 0.02872974 0.75557713 0.09399029 0.40960838

In [72]:
# get the default number of decimals

getOption('digits')

[1] 7

7 is the number of significant decimals. Internally, however, each number is stored with a 64 bits precision (up to 16 significant decimals). It can introduce errors sometimes:

In [73]:
sqrt(2) ^ 2 - 2

[1] 4.440892e-16

In [74]:
print(sqrt(2) ^ 2, digits = 22)

[1] 2.000000000000000444089


This is not exactly zero because the precision is 16 decimals. This kind of error is known as floating-point error. In R, numbers can be represented to up to 22 decimals:

In [75]:
print(x, digits=1)

 [1] 0.53 0.73 0.93 0.30 0.87 0.38 0.03 0.76 0.09 0.41


In [76]:
print(x, digits=7)

 [1] 0.52906946 0.72586459 0.92717495 0.29825008 0.87389428 0.37516016
 [7] 0.02872974 0.75557713 0.09399029 0.40960838


In [77]:
print(x, digits=22)

 [1] 0.52906945627182722091675 0.72586458525620400905609
 [3] 0.92717494629323482513428 0.29825007519684731960297
 [5] 0.87389427586458623409271 0.37516016233712434768677
 [7] 0.02872973866760730743408 0.75557712675072252750397
 [9] 0.09399028727784752845764 0.40960838040336966514587


In [78]:
# changing the display to scientific:

print(x, scientific=TRUE)

 [1] 0.52906946 0.72586459 0.92717495 0.29825008 0.87389428 0.37516016
 [7] 0.02872974 0.75557713 0.09399029 0.40960838


### 5.1.2. Sequence of numbers

In [79]:
seq(1, 10)

[1]  1  2  3  4  5  6  7  8  9 10

In [80]:
# same as

1:10

[1]  1  2  3  4  5  6  7  8  9 10

In [81]:
seq(from=1, to=10, by=2)

[1] 1 3 5 7 9

In [82]:
# 15 values between 1 and 10

seq(1, 10, length.out=15)

[1]  1.000000  1.642857  2.285714  2.928571  3.571429  4.214286  4.857143
 [8]  5.500000  6.142857  6.785714  7.428571  8.071429  8.714286  9.357143
[15] 10.000000

In [83]:
rep(1, 10)

[1] 1 1 1 1 1 1 1 1 1 1

In [84]:
rep(c(1, 2, 3), times = 5)

[1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3

In [85]:
rep(c(1, 2, 3), each=5)

[1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3

### 5.1.3. Mathematical operations with numeric vectors

In [86]:
# betweem vector and number

num * 2

[1] 20 10  4  8 16 18

In [87]:
# two vectors of the same size

num * num

[1] 100  25   4  16  64  81

In [88]:
# or multiple length

num * c(2, 4, 1)

[1] 20 20  2  8 32  9

### 5.1.4. Recycling rules

In [89]:
num / c(2, 4, 1, 3)

Warning message in num/c(2, 4, 1, 3):
“longer object length is not a multiple of shorter object length”

[1] 5.000000 1.250000 2.000000 1.333333 4.000000 2.250000

## 5.2. Other types of vectors

In [90]:
# characters

characters <- c('brava', 'joaquina', 'armação')
characters

[1] "brava"    "joaquina" "armação"

In [91]:
typeof(characters)

[1] "character"

In [92]:
class(characters)

[1] "character"

In [93]:
# logical

logical <- num > 4
logical

[1]  TRUE  TRUE FALSE FALSE  TRUE  TRUE

Some logical operators:

|||
|------------|
|**Operator**|**Test**|
|<|less than|
|<=|less than or equal to|
|>|greater than|
|>=|greater than or equal to|
|==|equal to|
|!=|different than|
|%in%|is contained in |

## 5.3. Mixing classes of objects

In [94]:
w <- c(5L, 'a')
x <- c(1.7, 'a')
y <- c(TRUE, 2)
z <- c('a', TRUE)

When different types are mixed up, **coercion** occurs, so that all elements are of the same class. Above we saw R's implicit coercion, but we can explicitly coerce elements using the `as.*` functions

In [95]:
x <- 0:6
typeof(x)

[1] "integer"

In [96]:
class(x)

[1] "integer"

In [97]:
as.numeric(x)

[1] 0 1 2 3 4 5 6

In [98]:
as.logical(x)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [99]:
as.character(x)

[1] "0" "1" "2" "3" "4" "5" "6"

In [100]:
as.factor(x)

[1] 0 1 2 3 4 5 6
Levels: 0 1 2 3 4 5 6

In [101]:
(x <- c(FALSE, TRUE))

[1] FALSE  TRUE

In [102]:
class(x)

[1] "logical"

In [103]:
as.numeric(x)

[1] 0 1

In [104]:
# sometimes it is not possible to coerce

x <- c('a', 'b', 'c')
as.numeric(x)

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] NA NA NA

In [105]:
as.logical(x)

[1] NA NA NA

## 5.4. Lost values and specials

Lost values are defined as `NA` (not available)

In [106]:
lost <- c(3, 5, NA, 2)
lost

[1]  3  5 NA  2

In [107]:
class(lost)

[1] "numeric"

In [108]:
# check to see if there are any NAs:

is.na(lost)

[1] FALSE FALSE  TRUE FALSE

In [109]:
any(is.na(lost))

[1] TRUE

Other special values are `NaN` (not a number), e.g. `0/0` and `-Inf` and `+Inf`, e.g. `1/0`, `is.na` also tests the presence of `NaN`

In [110]:
lost <- c(-1, 0, 1)/0
lost

[1] -Inf  NaN  Inf

In [111]:
is.na(lost)

[1] FALSE  TRUE FALSE

In [112]:
# test if there are infinite values

is.infinite(lost)

[1]  TRUE FALSE  TRUE

## 5.5. Exercise 3

In [113]:
# 1.

obj <- c(54, 0, 17, 94, 12.5, 2, 0.9, 15)

In [114]:
obj + c(5, 6)

[1]  59.0   6.0  22.0 100.0  17.5   8.0   5.9  21.0

In [115]:
obj + c(5, 6, 7)

Warning message in obj + c(5, 6, 7):
“longer object length is not a multiple of shorter object length”

[1] 59.0  6.0 24.0 99.0 18.5  9.0  5.9 21.0

In [116]:
# 2.

obj <- rep(c('A', 'B', 'C'), times=c(15, 12, 8))

In [117]:
obj == 'B'

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[25]  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [118]:
?sum

In [119]:
sum(obj == 'B')

[1] 12

In [120]:
# 3.

obj <- runif(n=100)

In [121]:
sum(obj >= 0.5)

[1] 46

In [122]:
# 4.

seq1 <- 2 ** seq(1, 50)
seq1

[1] 2.000000e+00 4.000000e+00 8.000000e+00 1.600000e+01 3.200000e+01
 [6] 6.400000e+01 1.280000e+02 2.560000e+02 5.120000e+02 1.024000e+03
[11] 2.048000e+03 4.096000e+03 8.192000e+03 1.638400e+04 3.276800e+04
[16] 6.553600e+04 1.310720e+05 2.621440e+05 5.242880e+05 1.048576e+06
[21] 2.097152e+06 4.194304e+06 8.388608e+06 1.677722e+07 3.355443e+07
[26] 6.710886e+07 1.342177e+08 2.684355e+08 5.368709e+08 1.073742e+09
[31] 2.147484e+09 4.294967e+09 8.589935e+09 1.717987e+10 3.435974e+10
[36] 6.871948e+10 1.374390e+11 2.748779e+11 5.497558e+11 1.099512e+12
[41] 2.199023e+12 4.398047e+12 8.796093e+12 1.759219e+13 3.518437e+13
[46] 7.036874e+13 1.407375e+14 2.814750e+14 5.629500e+14 1.125900e+15

In [123]:
seq2 <- seq(1, 50) ** 2
seq2

[1]    1    4    9   16   25   36   49   64   81  100  121  144  169  196  225
[16]  256  289  324  361  400  441  484  529  576  625  676  729  784  841  900
[31]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764 1849 1936 2025
[46] 2116 2209 2304 2401 2500

In [124]:
seq1[seq1 == seq2]

[1]  4 16

In [125]:
sum(seq1 == seq2)

[1] 2

In [126]:
sin <- sin(seq(0, 2 * pi, by=0.1))
cos <- cos(seq(0, 2 * pi, by=0.1))
tan <- tan(seq(0, 2 * pi, by=0.1))

In [127]:
tan2 <- sin / cos

In [128]:
tan - tan2

[1]  0.000000e+00  1.387779e-17  2.775558e-17  5.551115e-17  0.000000e+00
 [6]  0.000000e+00 -1.110223e-16 -1.110223e-16  0.000000e+00 -2.220446e-16
[11]  2.220446e-16 -2.220446e-16 -4.440892e-16 -4.440892e-16  0.000000e+00
[16] -1.776357e-15  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
[21]  0.000000e+00  0.000000e+00  2.220446e-16  0.000000e+00  0.000000e+00
[26]  0.000000e+00 -1.110223e-16  0.000000e+00  0.000000e+00  0.000000e+00
[31]  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
[36]  5.551115e-17  0.000000e+00  0.000000e+00  0.000000e+00 -1.110223e-16
[41]  0.000000e+00  0.000000e+00  0.000000e+00 -4.440892e-16  4.440892e-16
[46]  0.000000e+00  0.000000e+00  1.421085e-14  0.000000e+00  0.000000e+00
[51]  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
[56]  0.000000e+00 -1.110223e-16  0.000000e+00  0.000000e+00 -5.551115e-17
[61]  0.000000e+00  0.000000e+00  0.000000e+00

In [129]:
tan[tan == tan2]

[1]   0.00000000   0.42279322   0.54630249   1.02963856   5.79788372
 [6] -34.23253274  -7.69660214  -4.28626167  -2.92709751  -2.18503986
[11]  -1.70984654  -1.11921364  -0.91601429  -0.74702230  -0.47272763
[16]  -0.35552983  -0.24640539  -0.14254654  -0.04161665   0.05847385
[21]   0.15974575   0.26431690   0.49346673   0.62473308   0.77355609
[26]   1.15782128   1.42352648   1.77777977   4.63733205   8.86017490
[31] -11.38487065  -5.26749307  -3.38051501  -2.44938942  -1.88564188
[36]  -1.50127340  -1.21754082  -0.99558405  -0.65973057  -0.52466622
[41]  -0.29100619  -0.18526223  -0.08337771

In [130]:
max(abs(tan - tan2))

[1] 1.421085e-14

# 6. Other classes

## 6.1. Factor

Similar to `characters`, but stored and treated differently. `Factors` are a collection of categories or *levels*, unidimensional structure

In [131]:
factor <- factor(c('high', 'low', 'low', 'average',
                   'high', 'average', 'low', 'average', 'average'))
factor

[1] high    low     low     average high    average low     average average
Levels: average high low

In [132]:
class(factor)

[1] "factor"

In [133]:
typeof(factor)

[1] "integer"

Its class is factor, but its type is integer. Each class is internally represented as a number and factors have an ordering. When we remove a class from an object

In [134]:
unclass(factor)

[1] 2 3 3 1 2 1 3 1 1
attr(,"levels")
[1] "average" "high"    "low"

In [135]:
as.character(factor)

[1] "high"    "low"     "low"     "average" "high"    "average" "low"    
[8] "average" "average"

In [136]:
as.integer(factor)

[1] 2 3 3 1 2 1 3 1 1

In [137]:
# explicitly declaring levels

factor <- factor(c('high', 'low', 'low', 'average',
                   'high', 'average', 'low', 'average', 'average'),
                 levels = c('high', 'average', 'low'))
factor

[1] high    low     low     average high    average low     average average
Levels: high average low

In [138]:
# explicitly declaring levels and order

factor <- factor(c('high', 'low', 'low', 'average',
                   'high', 'average', 'low', 'average', 'average'),
                 levels = c('high', 'average', 'low'),
                 ordered=TRUE)
factor

[1] high    low     low     average high    average low     average average
Levels: high < average < low

In [139]:
typeof(factor)

[1] "integer"

In [140]:
class(factor)

[1] "ordered" "factor"

In [141]:
levels(factor)

[1] "high"    "average" "low"

In [142]:
nlevels(factor)

[1] 3

## 6.2. Matrix

Matrices are two-dimensional vectors, they can contain only one type of elements

In [143]:
matrix <- matrix(1:12, nrow=3, ncol=4)
matrix

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [144]:
class(matrix)

[1] "matrix"

In [145]:
typeof(matrix)

[1] "integer"

In [146]:
# changing the filling order

matrix <- matrix(1:12, nrow=3, ncol=4, byrow=TRUE)
matrix

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [147]:
# dimensions

dim(matrix)

[1] 3 4

In [148]:
# addind columns

cbind(matrix, rep(99, 3))

[,1] [,2] [,3] [,4] [,5]
[1,] 1     2    3    4   99  
[2,] 5     6    7    8   99  
[3,] 9    10   11   12   99

In [149]:
# adding rows

rbind(matrix, rep(99, 4))

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 99   99   99   99

matrices can be created from vectors by adding an dimensions attribute:

In [150]:
m <- 1:10
m

[1]  1  2  3  4  5  6  7  8  9 10

In [151]:
class(m)

[1] "integer"

In [152]:
dim(m)

NULL

In [153]:
dim(m) <- c(2, 5)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [154]:
class(m)

[1] "matrix"

In [155]:
typeof(m)

[1] "integer"

### 6.2.1. Matrices operations

In [156]:
# multiply by scalar

matrix * 2

[,1] [,2] [,3] [,4]
[1,]  2    4    6    8  
[2,] 10   12   14   16  
[3,] 18   20   22   24

In [157]:
# multiply by matrix

matrix2 <- matrix(1, nrow=4, ncol=3)
matrix %*% matrix2

[,1] [,2] [,3]
[1,] 10   10   10  
[2,] 26   26   26  
[3,] 42   42   42

## 6.3. Array

An array is a matrix with n dimensions

In [158]:
ar <- array(1:12, dim=c(2, 2, 3))
ar

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]   10   12

In [159]:
ar <- array(1:12, dim=c(3, 2, 2))
ar

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

## 6.4. List

In [160]:
list1 <- list(1:30, 'R', list(TRUE, FALSE))
list1

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30

[[2]]
[1] "R"

[[3]]
[[3]][[1]]
[1] TRUE

[[3]][[2]]
[1] FALSE

In [161]:
# check the structure

str(list1)

List of 3
 $ : int [1:30] 1 2 3 4 5 6 7 8 9 10 ...
 $ : chr "R"
 $ :List of 2
  ..$ : logi TRUE
  ..$ : logi FALSE


In [162]:
# unidimensional

dim(list1)

NULL

In [163]:
length(list1)

[1] 3

In [164]:
list2 <- list(factor, matrix)
list2

[[1]]
[1] high    low     low     average high    average low     average average
Levels: high < average < low

[[2]]
     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12

## 6.5. Dataframe

Dataframe is a bidimensional list in which each element must have the same length, each vector of the list becomes a column

In [165]:
df <- data.frame(nome=c('João', 'José', 'Maria'),
                 sexo=c('M', 'M', 'F'),
                 idade=c(32, 34, 30))
df

nome  sexo idade
1 João  M    32   
2 José  M    34   
3 Maria F    30

In [166]:
class(df)

[1] "data.frame"

In [167]:
typeof(df)

[1] "list"

In [168]:
dim(df)

[1] 3 3

In [169]:
str(df)

'data.frame':	3 obs. of  3 variables:
 $ nome : Factor w/ 3 levels "João","José",..: 1 2 3
 $ sexo : Factor w/ 2 levels "F","M": 2 2 1
 $ idade: num  32 34 30


In [170]:
length(num); length(factor)

[1] 6

[1] 9

In [171]:
df2 <- data.frame(numeric=c(num, NA, NA, NA),
                  factor=factor)
df2

numeric factor 
1 10      high   
2  5      low    
3  2      low    
4  4      average
5  8      high   
6  9      average
7 NA      low    
8 NA      average
9 NA      average

In [172]:
str(df2)

'data.frame':	9 obs. of  2 variables:
 $ numeric: num  10 5 2 4 8 9 NA NA NA
 $ factor : Ord.factor w/ 3 levels "high"<"average"<..: 1 3 3 2 1 2 3 2 2


In [173]:
# converting a data.frame to matrix
# converts to character

as.matrix(df2)

numeric factor 
 [1,] 10      high   
 [2,]  5      low    
 [3,]  2      low    
 [4,]  4      average
 [5,]  8      high   
 [6,]  9      average
 [7,] NA      low    
 [8,] NA      average
 [9,] NA      average

In [174]:
# converts to integer

data.matrix(df2)

numeric factor
 [1,] 10      1     
 [2,]  5      3     
 [3,]  2      3     
 [4,]  4      2     
 [5,]  8      1     
 [6,]  9      2     
 [7,] NA      3     
 [8,] NA      2     
 [9,] NA      2

# 7. Object attributes

It is a piece of information that can be attributed to an object without interfering with the actual values, they are seen as metadata. For example: `names`, `dimnames`, `dim`, `class`. They can all be seen with the `attributes()` function

In [175]:
x <- 1:6
attributes(x)

NULL

In [176]:
names(x) <- c('um', 'dois', 'três', 'quatro', 'cinco', 'seis')
names(x)

[1] "um"     "dois"   "três"   "quatro" "cinco"  "seis"

In [177]:
attributes(x)

$names
[1] "um"     "dois"   "três"   "quatro" "cinco"  "seis"

In [178]:
x

um   dois   três quatro  cinco   seis 
     1      2      3      4      5      6

In [179]:
# attributes can be removed using the NULL

names(x) <- NULL
attributes(x)

NULL

In [180]:
x

[1] 1 2 3 4 5 6

In [181]:
length(x)

[1] 6

In [182]:
length(x) <- 10
x

[1]  1  2  3  4  5  6 NA NA NA NA

In [183]:
length(x) <- 6
dim(x)

NULL

In [184]:
dim(x) <- c(3, 2)
x

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [185]:
attributes(x)

$dim
[1] 3 2

In [186]:
dim(x) <- NULL
x

[1] 1 2 3 4 5 6

In [187]:
# lists can also have names

x <- list(Curitiba = 1, Paraná = 2, Brasil = 3)
x

$Curitiba
[1] 1

$Paraná
[1] 2

$Brasil
[1] 3

In [188]:
names(x)

[1] "Curitiba" "Paraná"   "Brasil"

In [189]:
# associated names with matrices rows and columns

matrix

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [190]:
attributes(matrix)

$dim
[1] 3 4

In [191]:
rownames(matrix) <- c('A', 'B', 'C')
colnames(matrix) <- c('T1', 'T2', 'T3', 'T4')
matrix

T1 T2 T3 T4
A 1   2  3  4
B 5   6  7  8
C 9  10 11 12

In [192]:
attributes(matrix)

$dim
[1] 3 4

$dimnames
$dimnames[[1]]
[1] "A" "B" "C"

$dimnames[[2]]
[1] "T1" "T2" "T3" "T4"

In [193]:
# data.frames

df

nome  sexo idade
1 João  M    32   
2 José  M    34   
3 Maria F    30

In [194]:
attributes(df)

$names
[1] "nome"  "sexo"  "idade"

$row.names
[1] 1 2 3

$class
[1] "data.frame"

In [195]:
names(df)

[1] "nome"  "sexo"  "idade"

In [196]:
row.names(df)

[1] "1" "2" "3"

## 7.1. Exercise 4

In [197]:
# 1.

matrix <- matrix(c(2, 8, 4, 0, 4, 1, 9, 7, 5), nrow=3, ncol=3, byrow=T)
matrix

[,1] [,2] [,3]
[1,] 2    8    4   
[2,] 0    4    1   
[3,] 9    7    5

In [198]:
# 2.

rownames(matrix) <- c(1, 2, 3)
colnames(matrix) <- c('col1', 'col2', 'col3')
matrix

col1 col2 col3
1 2    8    4   
2 0    4    1   
3 9    7    5

In [199]:
# 3.

list3 <- list(rep(c('A', 'B', 'C'), times=c(2, 5, 4)), matrix)
list3

[[1]]
 [1] "A" "A" "B" "B" "B" "B" "B" "C" "C" "C" "C"

[[2]]
  col1 col2 col3
1    2    8    4
2    0    4    1
3    9    7    5

In [200]:
# 4.

names(list3) <- c('comp1', 'comp2')
list3

$comp1
 [1] "A" "A" "B" "B" "B" "B" "B" "C" "C" "C" "C"

$comp2
  col1 col2 col3
1    2    8    4
2    0    4    1
3    9    7    5

In [201]:
list3 <- list(list3, fator = factor(c('brava', 'joaquina', 'armação')))
list3

ERROR while rich displaying an object: Error in FUN(X[[i]], ...): attempt to use zero-length variable name

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     rpr <- mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     rpr <- mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. mime2repr[[mime]](obj)
8. repr_html.list(obj)
9. repr_list_generic(obj, "html", "\t<li>%s</li>\n", "\t<dt>$%s</dt>\n\t\t<dd>%s</dd>\n", 
 .     "<strong>$%s</strong> = %s", "<ol>\n%s</ol>\n", "<dl>\n%s</dl>\n", 
 .     numeric_item = "\t<dt>[[%s]]</dt>\n\t\t<dd>%s</dd>\n", escape_fun = html_escape)


[[1]]
[[1]]$comp1
 [1] "A" "A" "B" "B" "B" "B" "B" "C" "C" "C" "C"

[[1]]$comp2
  col1 col2 col3
1    2    8    4
2    0    4    1
3    9    7    5


$fator
[1] brava    joaquina armação 
Levels: armação brava joaquina


In [202]:
df <- data.frame(nome=c('João', 'Maria'),
                 sobrenome=c('Silva', 'Sauro'),
                 animal=c(TRUE, FALSE),
                 quantidadeAnimal=c(2,0))
df

nome  sobrenome animal quantidadeAnimal
1 João  Silva      TRUE  2               
2 Maria Sauro     FALSE  0

In [203]:
df <- rbind(df, data.frame(nome='José', sobrenome='Santos', animal=TRUE, quantidadeAnimal=5))
df

nome  sobrenome animal quantidadeAnimal
1 João  Silva      TRUE  2               
2 Maria Sauro     FALSE  0               
3 José  Santos     TRUE  5

In [204]:
df <- cbind(df, data.frame(time=c('Inter', 'Grêmio', 'Juventude')))
df

nome  sobrenome animal quantidadeAnimal time     
1 João  Silva      TRUE  2                Inter    
2 Maria Sauro     FALSE  0                Grêmio   
3 José  Santos     TRUE  5                Juventude

# 8. Object-oriented programming

In [205]:
methods(mean)

[1] mean.Date     mean.default  mean.difftime mean.POSIXct  mean.POSIXlt 
see '?methods' for accessing help and source code

In [206]:
set.seed(42)
vec <- rnorm(100)
class(vec)

[1] "numeric"

In [207]:
mean(vec)

[1] 0.03251482

There is a specific method defined to the numeric class, which is the mean.default. The generic function is the `mean()` and the method function is the `mean.default()`

In [208]:
mean.default(vec)

[1] 0.03251482

In [209]:
# we could force other method

mean.Date(vec)

[1] "1970-01-01"

In [210]:
mean

function (x, ...) 
UseMethod("mean")
<bytecode: 0x556056cc5c18>
<environment: namespace:base>

In [211]:
mean.default

function (x, trim = 0, na.rm = FALSE, ...) 
{
    if (!is.numeric(x) && !is.complex(x) && !is.logical(x)) {
        warning("argument is not numeric or logical: returning NA")
        return(NA_real_)
    }
    if (na.rm) 
        x <- x[!is.na(x)]
    if (!is.numeric(trim) || length(trim) != 1L) 
        stop("'trim' must be numeric of length one")
    n <- length(x)
    if (trim > 0 && n) {
        if (is.complex(x)) 
            stop("trimmed means are not defined for complex data")
        if (anyNA(x)) 
            return(NA_real_)
        if (trim >= 0.5) 
            return(stats::median(x, na.rm = FALSE))
        lo <- floor(n * trim) + 1
        hi <- n + 1 - lo
        x <- sort.int(x, partial = unique(c(lo, hi)))[lo:hi]
    }
    .Internal(mean(x))
}
<bytecode: 0x556056c59880>
<environment: namespace:base>

In [212]:
# suppose we want the row mean

mat <- matrix(rnorm(50), nrow=5)
mean(mat)
# not what we want

[1] -0.1512511

In [213]:
# we could define a custom function for that

mean.matrix <- function(x, ...) rowMeans(x)

In [214]:
methods(mean)

[1] mean.Date     mean.default  mean.difftime mean.matrix   mean.POSIXct 
[6] mean.POSIXlt 
see '?methods' for accessing help and source code

In [215]:
class(mat)

[1] "matrix"

In [216]:
mean(mat)

[1] -0.05250455 -0.38450584 -0.04853703 -0.07304678 -0.19766125

We could do the same for other classes, such as dataframes, lists etc.