In [1]:
from array import *

In [3]:
meuVetor = array('i', [1, 2, 3])
outroVetor = array('i', [4, 5, 6])

In [4]:
# can only extend same type of vector

meuVetor.extend(outroVetor)

In [5]:
meuVetor

array('i', [1, 2, 3, 4, 5, 6])

In [6]:
meuVetor.reverse()
meuVetor

array('i', [6, 5, 4, 3, 2, 1])

In [7]:
meuVetor.remove(4)
meuVetor

array('i', [6, 5, 3, 2, 1])

In [8]:
meuVetor.index(2)

3

In [9]:
len(meuVetor)

5

In [10]:
type(meuVetor)

array.array

In [16]:
charArray = array('u', ['a', 'b', 'a'])
charArray

array('u', 'aba')

In [17]:
charArray = array('u', 'hello \u2641')
charArray

array('u', 'hello ♁')

In [18]:
import numpy as np

In [19]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [20]:
type(a)

numpy.ndarray

In [21]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
b.ndim

2

In [25]:
c = np.array([[[0, 1, 2], [3, 4, 5]], [[0, 1, 2], [3, 4, 5]]])
c

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [26]:
c.ndim

3

In [27]:
c.shape

(2, 2, 3)

In [28]:
a.size

3

In [29]:
a.dtype

dtype('int64')

In [31]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [39]:
np.ones((2, 3), dtype = np.int64)

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
np.pi

3.141592653589793

In [41]:
np.random.rand(2, 3)

array([[0.53147446, 0.26655835, 0.15962007],
       [0.40730301, 0.412978  , 0.75381996]])

In [43]:
np.random.rand(2, 3, 4, 5)

array([[[[0.45840266, 0.26721705, 0.24287986, 0.83107747, 0.61223791],
         [0.88369768, 0.42025187, 0.79507519, 0.17557362, 0.34924357],
         [0.00190268, 0.21802729, 0.84861718, 0.705507  , 0.69735586],
         [0.46560617, 0.58435603, 0.68942344, 0.06194002, 0.18008197]],

        [[0.41218496, 0.1652786 , 0.83987373, 0.31273768, 0.83150241],
         [0.3007972 , 0.67192242, 0.12954955, 0.44207889, 0.46066023],
         [0.33248225, 0.14502793, 0.920389  , 0.100273  , 0.69801187],
         [0.51599069, 0.42575667, 0.21331586, 0.52821135, 0.07865574]],

        [[0.21461156, 0.02214476, 0.02687798, 0.29900952, 0.32089504],
         [0.60299079, 0.96802775, 0.5918248 , 0.39378087, 0.02448996],
         [0.40445749, 0.3802906 , 0.66953204, 0.51889651, 0.73981758],
         [0.07049211, 0.26187184, 0.92881122, 0.89860553, 0.10995283]]],


       [[[0.38900852, 0.57573191, 0.49558765, 0.01269107, 0.80228735],
         [0.06206991, 0.31934967, 0.51334189, 0.48775178, 0.94929261]

In [61]:
np.empty((3, 3))

array([[6.93114633e-310, 1.73456488e-316, 6.93112465e-310],
       [6.93112464e-310, 6.93112464e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [62]:
np.full((2, 3), 3)

array([[3, 3, 3],
       [3, 3, 3]])

In [63]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [64]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [72]:
np.savetxt('teste.txt', b)

In [68]:
!cat teste.txt

0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00
3.000000000000000000e+00 4.000000000000000000e+00 5.000000000000000000e+00


In [74]:
np.savetxt('teste.txt', b, delimiter = ',')

In [75]:
!cat teste.txt

0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00
3.000000000000000000e+00,4.000000000000000000e+00,5.000000000000000000e+00


In [76]:
np.loadtxt('teste.txt', delimiter = ',')

array([[0., 1., 2.],
       [3., 4., 5.]])

In [94]:
!ls ./data

2018_04_28_33MUE250GC_SIR.cpg  2018_04_28_pop2016.csv
2018_04_28_33MUE250GC_SIR.dbf  2018_05_25_SacramentocrimeJanuary2006.csv
2018_04_28_33MUE250GC_SIR.prj  2018_05_25_TaubateMissing.csv
2018_04_28_33MUE250GC_SIR.shp  2018_05_25_uma_lista_exemplo.txt
2018_04_28_33MUE250GC_SIR.shx


In [79]:
!cat data/2018_05_25_TaubateMissing.csv














Year,40.1,27.7,20.4,15.8,0.9,1396.8,111,74.5,2045.9

In [95]:
np.loadtxt('./data/2018_05_25_TaubateMissing.csv',
           dtype = {'format': (np.str, np.float, np.float, np.float, np.float, np.float, np.float, np.float, np.float, np.float)},
           delimiter = ',',
           skiprows = 1)

ValueError: entry not a 2- or 3- tuple

In [97]:
np.genfromtxt('./data/2018_05_25_TaubateMissing.csv', skip_header=1, delimiter=',')

array([[       nan, 3.6700e+01, 3.0200e+01, 2.3300e+01, 1.7700e+01,
        1.0900e+01, 2.3350e+02, 1.7000e+01, 7.6800e+01, 1.7000e+02],
       [       nan, 4.0100e+01, 3.0500e+01, 2.3500e+01, 1.7800e+01,
        1.2600e+01, 1.9210e+02, 1.4000e+01, 7.6700e+01, 1.6820e+02],
       [       nan, 3.6200e+01, 2.9900e+01, 2.2900e+01, 1.7800e+01,
        1.1600e+01, 1.7350e+02, 1.2000e+01, 7.6800e+01, 1.7950e+02],
       [       nan, 3.4200e+01,        nan, 2.0800e+01, 1.6100e+01,
        5.4000e+00, 6.7100e+01, 7.0000e+00, 7.5900e+01, 1.7730e+02],
       [       nan, 3.2600e+01, 2.5400e+01, 1.8100e+01, 1.4200e+01,
        4.2000e+00, 4.0900e+01, 4.0000e+00, 7.6200e+01, 1.7610e+02],
       [       nan, 3.1000e+01, 2.4600e+01, 1.6700e+01, 1.2900e+01,
        1.1000e+00,        nan, 4.0000e+00, 7.5700e+01, 1.7560e+02],
       [       nan, 3.2100e+01, 2.4400e+01, 1.6400e+01, 1.2600e+01,
        9.0000e-01, 3.1100e+01, 4.0000e+00, 7.2500e+01, 1.8890e+02],
       [       nan, 3.5600e+01, 2.6400e+0

In [98]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv  --directory-prefix="/home/jayme/dsbd/programming_languages_for_data_science/data/"

--2018-06-09 10:55:39--  https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 264426 (258K) [text/csv]
Saving to: ‘/home/jayme/dsbd/programming_languages_for_data_science/data/winequality-white.csv’

winequality-white.c 100%[===================>] 258,23K   121KB/s    in 2,1s    

2018-06-09 10:55:47 (121 KB/s) - ‘/home/jayme/dsbd/programming_languages_for_data_science/data/winequality-white.csv’ saved [264426/264426]



In [100]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv  --directory-prefix="/home/jayme/dsbd/programming_languages_for_data_science/data/"

--2018-06-09 10:56:24--  https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.249
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84199 (82K) [text/csv]
Saving to: ‘/home/jayme/dsbd/programming_languages_for_data_science/data/winequality-red.csv’

winequality-red.csv 100%[===================>]  82,23K  64,8KB/s    in 1,3s    

2018-06-09 10:56:33 (64,8 KB/s) - ‘/home/jayme/dsbd/programming_languages_for_data_science/data/winequality-red.csv’ saved [84199/84199]



In [101]:
!ls ./data/

2018_04_28_33MUE250GC_SIR.cpg  2018_05_25_SacramentocrimeJanuary2006.csv
2018_04_28_33MUE250GC_SIR.dbf  2018_05_25_TaubateMissing.csv
2018_04_28_33MUE250GC_SIR.prj  2018_05_25_uma_lista_exemplo.txt
2018_04_28_33MUE250GC_SIR.shp  winequality-red.csv
2018_04_28_33MUE250GC_SIR.shx  winequality-white.csv
2018_04_28_pop2016.csv


In [102]:
!mv ./data/winequality-red.csv "./data/2018_06_09_winequality-red.csv"
!mv ./data/winequality-white.csv "./data/2018_06_09_winequality-white.csv"

In [103]:
!ls ./data/

2018_04_28_33MUE250GC_SIR.cpg  2018_05_25_SacramentocrimeJanuary2006.csv
2018_04_28_33MUE250GC_SIR.dbf  2018_05_25_TaubateMissing.csv
2018_04_28_33MUE250GC_SIR.prj  2018_05_25_uma_lista_exemplo.txt
2018_04_28_33MUE250GC_SIR.shp  2018_06_09_winequality-red.csv
2018_04_28_33MUE250GC_SIR.shx  2018_06_09_winequality-white.csv
2018_04_28_pop2016.csv


In [179]:
red = np.genfromtxt('./data/2018_06_09_winequality-red.csv',
                    delimiter = ';',
#                     skip_header = 1,
                    names = True,
                    unpack = True)

In [175]:
white = np.genfromtxt('./data/2018_06_09_winequality-white.csv',
                      delimiter = ';',
#                       skip_header = 1,
                      names = True)

In [178]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
   

In [183]:
red

array([(7.4, 0.7  , 0.  , 1.9, 0.076, 11., 34., 0.9978 , 3.51, 0.56,  9.4, 5.),
       (7.8, 0.88 , 0.  , 2.6, 0.098, 25., 67., 0.9968 , 3.2 , 0.68,  9.8, 5.),
       (7.8, 0.76 , 0.04, 2.3, 0.092, 15., 54., 0.997  , 3.26, 0.65,  9.8, 5.),
       ...,
       (6.3, 0.51 , 0.13, 2.3, 0.076, 29., 40., 0.99574, 3.42, 0.75, 11. , 6.),
       (5.9, 0.645, 0.12, 2. , 0.075, 32., 44., 0.99547, 3.57, 0.71, 10.2, 5.),
       (6. , 0.31 , 0.47, 3.6, 0.067, 18., 42., 0.99549, 3.39, 0.66, 11. , 6.)],
      dtype=[('fixed_acidity', '<f8'), ('volatile_acidity', '<f8'), ('citric_acid', '<f8'), ('residual_sugar', '<f8'), ('chlorides', '<f8'), ('free_sulfur_dioxide', '<f8'), ('total_sulfur_dioxide', '<f8'), ('density', '<f8'), ('pH', '<f8'), ('sulphates', '<f8'), ('alcohol', '<f8'), ('quality', '<f8')])

In [239]:
new_red = np.array([i for i in range(len(red))])[:, np.newaxis]

for col in red.dtype.fields.keys():
    new_red = np.append(new_red, red[col][:, np.newaxis], axis = 1)

In [254]:
new_red = new_red[:, 1:]

In [262]:
red.dtype.names

('fixed_acidity',
 'volatile_acidity',
 'citric_acid',
 'residual_sugar',
 'chlorides',
 'free_sulfur_dioxide',
 'total_sulfur_dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality')

In [267]:
new_red.dtype.names

In [269]:
new_red.dtype.names = red.dtype.names

ValueError: there are no fields defined

In [244]:
red.dtype.fields.keys()

dict_keys(['fixed_acidity', 'sulphates', 'residual_sugar', 'density', 'pH', 'chlorides', 'quality', 'free_sulfur_dioxide', 'alcohol', 'volatile_acidity', 'total_sulfur_dioxide', 'citric_acid'])

In [182]:
red.shape

(1599,)

In [156]:
red = red[:, np.newaxis]

In [165]:
vinho = np.array(['red' for i in range(len(red))])

In [169]:
vinho = vinho[:, np.newaxis]

In [173]:
red.shape, vinho.shape

((1599, 1), (1599, 1))

In [193]:
np.append(red, vinho, axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [124]:
wine = np.concatenate((red, white))

In [125]:
np.savetxt('./data/2018_06_09_wine.csv', wine, delimiter = ',')